
import React, { useState } from 'react';
import { STOCKS } from '../constants';
import { StockInfo } from '../types';
import SummaryCard from '../components/SummaryCard';
import { Shield, TrendingUp, AlertCircle, CheckCircle2, XCircle, MinusCircle } from 'lucide-react';

const PredictionCenter: React.FC = () => {
  const [selectedStock, setSelectedStock] = useState<StockInfo>(STOCKS[0]);

  const getRiskColor = (confidence: number) => {
    if (confidence > 0.8) return 'text-emerald-500 bg-emerald-500/10';
    if (confidence > 0.6) return 'text-amber-500 bg-amber-500/10';
    return 'text-rose-500 bg-rose-500/10';
  };

  const getSignalIcon = (pred: string) => {
    if (pred === 'Buy') return <CheckCircle2 className="w-6 h-6 text-emerald-500" />;
    if (pred === 'Avoid') return <XCircle className="w-6 h-6 text-rose-500" />;
    return <MinusCircle className="w-6 h-6 text-slate-400" />;
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <header>
        <h2 className="text-3xl font-bold text-white">Prediction Center</h2>
        <p className="text-slate-400">High-confidence trading signals generated by the Transformer+LSTM hybrid model.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-4 bg-slate-800/40 border border-slate-700/50 p-6 rounded-2xl overflow-y-auto max-h-[700px]">
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-6">Ticker Watchlist</h3>
          <div className="space-y-3">
            {STOCKS.map(stock => (
              <button 
                key={stock.ticker}
                onClick={() => setSelectedStock(stock)}
                className={`w-full flex items-center justify-between p-4 rounded-xl transition-all border ${
                  selectedStock.ticker === stock.ticker 
                  ? 'bg-blue-600/10 border-blue-500/50' 
                  : 'bg-slate-900/50 border-slate-700/50 hover:border-slate-500'
                }`}
              >
                <div className="text-left">
                  <p className="font-bold text-white mono">{stock.ticker}</p>
                  <p className="text-[10px] text-slate-500">{stock.name}</p>
                </div>
                <div className="text-right">
                  <p className={`text-sm font-bold ${stock.change > 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                    {stock.change > 0 ? '+' : ''}{stock.change}%
                  </p>
                  <p className="text-[10px] text-slate-500">Vol: 1.2M</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        <div className="lg:col-span-8 space-y-8">
          <div className="bg-slate-800/40 border border-slate-700/50 p-8 rounded-2xl relative overflow-hidden">
            <div className="absolute top-0 right-0 p-8 opacity-5">
              <TrendingUp size={240} />
            </div>
            
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-12">
              <div className="flex items-center gap-4">
                <div className="p-4 bg-blue-500/10 rounded-2xl border border-blue-500/20">
                  <h4 className="text-4xl font-black text-white mono">{selectedStock.ticker}</h4>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-white">{selectedStock.name}</h3>
                  <div className="flex gap-2 mt-1">
                    <span className="text-xs px-2 py-0.5 bg-slate-700 text-slate-300 rounded">S&P 500</span>
                    <span className="text-xs px-2 py-0.5 bg-slate-700 text-slate-300 rounded">Technology</span>
                  </div>
                </div>
              </div>
              
              <div className="text-right">
                <p className="text-slate-500 text-sm mb-1 uppercase tracking-tighter font-bold">Recommended Action</p>
                <div className="flex items-center gap-2 justify-end">
                  {getSignalIcon(selectedStock.prediction)}
                  <span className={`text-4xl font-black uppercase tracking-tight ${
                    selectedStock.prediction === 'Buy' ? 'text-emerald-500' :
                    selectedStock.prediction === 'Avoid' ? 'text-rose-500' : 'text-slate-400'
                  }`}>
                    {selectedStock.prediction}
                  </span>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-6 bg-slate-900/50 border border-slate-700/50 rounded-2xl">
                <div className="flex items-center gap-2 text-slate-400 mb-2">
                  <Shield className="w-4 h-4" />
                  <span className="text-xs font-bold uppercase">Risk Level</span>
                </div>
                <div className={`text-lg font-bold px-3 py-1 rounded-lg inline-block ${getRiskColor(selectedStock.confidence)}`}>
                  {selectedStock.confidence > 0.8 ? 'LOW' : selectedStock.confidence > 0.6 ? 'MEDIUM' : 'HIGH'}
                </div>
                <p className="text-xs text-slate-500 mt-3">Based on 30-day volatility and sentiment variance.</p>
              </div>

              <div className="p-6 bg-slate-900/50 border border-slate-700/50 rounded-2xl">
                <div className="flex items-center gap-2 text-slate-400 mb-2">
                  <AlertCircle className="w-4 h-4" />
                  <span className="text-xs font-bold uppercase">Confidence</span>
                </div>
                <div className="text-3xl font-bold text-white mono">
                  {(selectedStock.confidence * 100).toFixed(1)}%
                </div>
                <div className="w-full bg-slate-800 h-1.5 rounded-full mt-4 overflow-hidden">
                  <div 
                    className="h-full bg-blue-500"
                    style={{ width: `${selectedStock.confidence * 100}%` }}
                  ></div>
                </div>
              </div>

              <div className="p-6 bg-slate-900/50 border border-slate-700/50 rounded-2xl">
                <div className="flex items-center gap-2 text-slate-400 mb-2">
                  <TrendingUp className="w-4 h-4" />
                  <span className="text-xs font-bold uppercase">Predicted Alpha</span>
                </div>
                <div className="text-3xl font-bold text-emerald-500 mono">
                  +{(selectedStock.sentimentScore * 4).toFixed(2)}%
                </div>
                <p className="text-xs text-slate-500 mt-3">Projected excess return over SPY in 5-day horizon.</p>
              </div>
            </div>
          </div>

          <div className="bg-slate-800/40 border border-slate-700/50 p-8 rounded-2xl">
            <h3 className="text-xl font-bold text-white mb-6">Prediction Confidence Bands</h3>
            <div className="space-y-6">
              <div className="relative h-24 bg-slate-900/50 rounded-xl overflow-hidden flex items-center justify-center border border-slate-700/50">
                <div className="absolute inset-y-0 left-[20%] right-[20%] bg-blue-500/10 border-x border-blue-500/20"></div>
                <div className="absolute inset-y-0 left-1/2 -translate-x-1/2 w-0.5 bg-blue-500 h-full"></div>
                <div 
                  className="absolute w-4 h-4 bg-white rounded-full border-2 border-blue-500 shadow-[0_0_15px_rgba(59,130,246,0.5)] transition-all duration-500"
                  style={{ left: `${(selectedStock.sentimentScore * 60) + 20}%` }}
                ></div>
                <div className="z-10 text-[10px] text-slate-500 font-bold uppercase tracking-widest flex w-full justify-between px-8">
                  <span>Bearish Zone</span>
                  <span>Signal Equilibrium</span>
                  <span>Bullish Zone</span>
                </div>
              </div>
              <p className="text-xs text-slate-400 text-center italic">
                The current prediction for {selectedStock.ticker} sits in the <span className="text-blue-400 font-bold">{selectedStock.sentimentScore > 0.5 ? 'Optimistic' : 'Conservative'}</span> band of our Monte Carlo model distribution.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PredictionCenter;
